### ISSUE TITLE
Verify that it works on Windows

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-org/r3bl_ansi_color#2]
Include a screenshot of the example (started using `run.fish`) running on Windows. This can go in the `README.md` & `lib.rs` files.

**Comment by andrewo37** [comment]
Tested and verified running on 8/20/23
![Screenshot 2023-08-20 205327](https://github.com/r3bl-org/r3bl_ansi_color/assets/52469857/e7769aa6-d11a-4c48-9ac5-01d43f37b027)

**Comment by nazmulidris** [comment]
@andrewo37 Thank you for your contribution! 👍🏽

**Comment by andrewo37** [comment]
![terminal_2](https://github.com/r3bl-org/r3bl_ansi_color/assets/52469857/50991c47-cc5a-4637-b8b4-0e70d963a744)
